version : "3"
services:
  mariadb_container:
    restart: always
    build: ./db_container/
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - main_network
    volumes:
      - DB:/var/lib/mysql/
    env_file:
      - ./.env

  nginx_container:
    restart: always
    build: ./nginx_container/
    image: nginx
    ports:
      - 443:443
    networks:
    - main_network
    volumes:
      - WordPress:/var/www/html/wordpress
    depends_on:
      - wordpress_container
    extra_hosts:
      - "khafni.42.fr:127.0.0.1"
 
  wordpress_container:
    restart: always
    build: ./wp_container/
    image: wordpress
    ports:
      - 9000:9000
    networks:
      - main_network
    volumes:
      - WordPress:/var/www/html/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb_container


networks:
  main_network:
    driver: bridge

volumes:
  DB:
    driver_opts:
      type: none
      device: /home/khafni/data/DB
      o: bind
  WordPress: 
    driver_opts:
      type: none
      device: /home/khafni/data/wordPress 
      o: bind
